# Generated by Django 3.0.5 on 2021-04-07 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del modulo', max_length=50)),
                ('submodulo', models.CharField(help_text='Nombre del submodulo', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del modulo', max_length=50)),
                ('idModulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bots.Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('Te', 'Terminado'), ('In', 'Iniciado'), ('Pr', 'Procesando'), ('Pa', 'Pausado'), ('Re', 'Reintentando'), ('Er', 'Error')], max_length=2)),
                ('mensaje', models.CharField(help_text='El mensaje a mostrar al usuario', max_length=100, null=True)),
                ('fechaInicio', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('fechaFin', models.DateTimeField(null=True)),
                ('tiempoEjecucion', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('porcentajeAvance', models.IntegerField(null=True)),
                ('idTarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bots.Tarea')),
            ],
        ),
    ]
