# Generated by Django 3.0.5 on 2021-04-07 03:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacencentrocosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacenASW', models.CharField(help_text='Id del alamcen en ASW', max_length=3)),
                ('centroCostosSAP', models.CharField(help_text='Id del Centro de Costos e  SAP', max_length=8)),
                ('descripcioncentroCostos', models.CharField(help_text='Nombre del Centro de Costos', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parteCuenta1', models.CharField(help_text='Parte de la cuenta 1', max_length=5)),
                ('parteCuenta2', models.CharField(help_text='Parte de la cuenta 2', max_length=5)),
                ('parteCuenta3', models.CharField(help_text='Parte de la cuenta 3', max_length=5)),
                ('factura', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('peridodContable', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('journalNumber', models.CharField(help_text='Nombre del canal', max_length=8)),
                ('monedaTransaccion', models.CharField(help_text='Moneda de transaccion', max_length=3)),
                ('montoMonedasistema', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montoMonedatransaccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.CharField(help_text='Descripción del descuento', max_length=100)),
                ('tipo', models.CharField(help_text='Tipo de descuento', max_length=3)),
                ('cantidad', models.IntegerField(null=True)),
                ('fechaFactura', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interfaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCarga', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nombreArchivo', models.CharField(help_text='Nombre Archivo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marcaarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaASW', models.CharField(help_text='Nombre de la Marca', max_length=3)),
                ('areanegocioSAP', models.CharField(help_text='Nombre del Area de negocio', max_length=3)),
                ('descripcionMarca', models.CharField(help_text='Descripcion Marca', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Polizafee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('idVentaASW', models.CharField(help_text='Nombre del Area de negocio', max_length=3)),
                ('idAlmacenvscentrocosto', models.CharField(help_text='Descripcion Marca', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(help_text='Abreviacion del segmento del producto', max_length=50)),
                ('descripcion', models.CharField(help_text='Nombre del segmento del producto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UUID_ASW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(help_text='Abreviacion del segmento del producto', max_length=50)),
                ('factura', models.CharField(help_text='Nombre del segmento del producto', max_length=10)),
                ('fechaFactura', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('UUID', models.CharField(help_text='UUID de la factura', max_length=50)),
                ('metodoPago', models.CharField(help_text='Método de pago de la factura', max_length=3)),
                ('usoCFDI', models.CharField(help_text='Uso de CFDI', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ventasSAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.IntegerField(null=True)),
                ('tipoDocumento', models.CharField(help_text='Tipo de documento', max_length=8)),
                ('fechaDocumento', models.DateTimeField(blank=True)),
                ('fechaPosteo', models.DateTimeField(blank=True)),
                ('periodoPosteo', models.IntegerField(null=True)),
                ('llavePosteo', models.IntegerField(null=True)),
                ('codigoTax', models.CharField(help_text='Codigo Tax', max_length=3)),
                ('montoMonedadocumento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(help_text='Moneda', max_length=3)),
                ('montoMonedasistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('areaNegocio', models.CharField(help_text='Area de negocio ', max_length=3)),
                ('centroCostos', models.CharField(help_text='Centro de costos', max_length=10)),
                ('descripcionCentrocostos', models.CharField(help_text='Descripcion del centro de costos', max_length=100)),
                ('descripcionCuentacontable', models.CharField(help_text='Descripción Cuenta Contable', max_length=100)),
                ('referenciaFactura', models.CharField(help_text='Referencia de la Factura', max_length=10)),
                ('cuentaContable', models.CharField(help_text='Cuenta Contable', max_length=100, null=True)),
                ('especialGL', models.CharField(help_text='Especial GL', max_length=100, null=True)),
                ('monedaLocal', models.CharField(help_text='Moneda Local', max_length=5, null=True)),
                ('documentoCompensacion', models.IntegerField(null=True)),
                ('cliente', models.IntegerField(null=True)),
                ('metodoPago', models.IntegerField(null=True)),
                ('textoExistente', models.CharField(help_text='Texto Existente', max_length=200, null=True)),
                ('bloqueoPago', models.CharField(help_text='Bloqueo de pago', max_length=100, null=True)),
                ('fechaVencimiento', models.DateTimeField(blank=True)),
                ('canal', models.CharField(help_text='Especial GL', max_length=20)),
                ('fuente', models.CharField(choices=[('R', 'Retail'), ('W', 'Wholesale')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ventasASW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monedaTransaccion', models.CharField(help_text='Moneda en la que fue realizada la transaccion', max_length=3)),
                ('journalNumber', models.IntegerField(null=True)),
                ('peridodContable', models.DateTimeField(blank=True)),
                ('factura', models.CharField(help_text='Tipo de documento', max_length=10)),
                ('grupo', models.CharField(help_text='Grupo', max_length=5)),
                ('cliente', models.CharField(help_text='Descripción del cliente', max_length=100)),
                ('nombreCliente', models.CharField(help_text='Tipo de documento', max_length=100)),
                ('fechaFactura', models.DateTimeField(blank=True)),
                ('tipoFactura2NC', models.IntegerField(null=True)),
                ('producto', models.CharField(help_text='Descripción del producto', max_length=10)),
                ('descuento', models.CharField(help_text='Descripcion del descuento', max_length=100)),
                ('pedido', models.IntegerField(null=True)),
                ('valorNeto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField(null=True)),
                ('grupoCuenta', models.CharField(help_text='Grupo de la cuenta', max_length=2)),
                ('categoriaProducto1', models.CharField(help_text='Categoria del producto 1', max_length=100)),
                ('categoriaProducto2', models.CharField(help_text='Categoria del producto 2', max_length=5, null=True)),
                ('categoriaProducto3', models.CharField(help_text='Categoria del producto 3', max_length=5, null=True)),
                ('categoriaProducto4', models.CharField(help_text='Categoria del producto 4', max_length=5, null=True)),
                ('categoriaProducto5', models.CharField(help_text='Categoria del producto 5', max_length=5, null=True)),
                ('categoriaPodructo6', models.CharField(help_text='Categoria del producto 6', max_length=5)),
                ('tipoOrden', models.IntegerField(null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('perido', models.DateTimeField(blank=True)),
                ('libreCargo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('idAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Almacencentrocosto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Marcaarea')),
            ],
        ),
        migrations.CreateModel(
            name='Cuadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(help_text='Nombre del canal', max_length=8)),
                ('totalASW', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('totalSAP', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fechaCreacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('factura', models.CharField(help_text='Nombre del canal', max_length=8)),
                ('fuente', models.CharField(choices=[('R', 'Retail'), ('W', 'Wholesale')], max_length=1)),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Marcaarea')),
            ],
        ),
    ]
