# Generated by Django 3.0.5 on 2021-04-08 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_ventassap_fechainsercion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventassap',
            name='canal',
            field=models.CharField(help_text='Especial GL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 9, 54, 35, 351556)),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaVencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fuente',
            field=models.CharField(choices=[('R', 'Retail'), ('W', 'Wholesale')], max_length=1, null=True),
        ),
    ]
