# Generated by Django 3.0.5 on 2021-04-08 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_auto_20210408_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 14, 5, 31, 613809)),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='referenciaFactura',
            field=models.CharField(help_text='Referencia de la Factura', max_length=20),
        ),
    ]
