# Generated by Django 3.0.5 on 2021-04-08 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_auto_20210408_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 17, 57, 55, 576427)),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaPosteo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
