# Generated by Django 3.0.5 on 2021-04-08 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_auto_20210408_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 17, 59, 51, 430932)),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='montoMonedadocumento',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
