# Generated by Django 3.0.5 on 2021-04-08 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_auto_20210408_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventassap',
            name='documentoCompensacion',
            field=models.CharField(help_text='Moneda Local', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 18, 3, 34, 167133)),
        ),
    ]
