# Generated by Django 3.0.5 on 2021-04-12 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0008_auto_20210408_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasasw',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='ventasasw',
            name='journalNumber',
        ),
        migrations.RemoveField(
            model_name='ventasasw',
            name='monedaTransaccion',
        ),
        migrations.RemoveField(
            model_name='ventasasw',
            name='perido',
        ),
        migrations.RemoveField(
            model_name='ventasasw',
            name='peridodContable',
        ),
        migrations.RemoveField(
            model_name='ventasasw',
            name='tipoFactura2NC',
        ),
        migrations.AddField(
            model_name='descuento',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 18, 50, 636754)),
        ),
        migrations.AddField(
            model_name='uuid_asw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 18, 50, 640741)),
        ),
        migrations.AddField(
            model_name='ventasasw',
            name='descripcionCategoria1',
            field=models.CharField(help_text='Categoria del producto 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventasasw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 18, 50, 653749)),
        ),
        migrations.AddField(
            model_name='ventasasw',
            name='periodoContable',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='categoriaProducto1',
            field=models.CharField(help_text='Categoria del producto 1', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='libreCargo',
            field=models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 18, 50, 653749)),
        ),
    ]
