# Generated by Django 3.0.5 on 2021-04-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0010_auto_20210412_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 28, 52, 165499)),
        ),
        migrations.AlterField(
            model_name='uuid_asw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 28, 52, 170473)),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 28, 52, 184463)),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='idAlmacen',
            field=models.CharField(help_text='Grupo', max_length=5),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 28, 52, 185432)),
        ),
    ]
