# Generated by Django 3.0.5 on 2021-04-12 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0011_auto_20210412_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasasw',
            name='factura',
            field=models.CharField(help_text='No de Factura', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventasasw',
            name='tipoFactura2NC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 52, 48, 104084)),
        ),
        migrations.AlterField(
            model_name='uuid_asw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 52, 48, 107067)),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='descuento',
            field=models.CharField(help_text='Descripcion del descuento', max_length=150),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 52, 48, 119585)),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='idAlmacen',
            field=models.CharField(help_text='Bodega', max_length=5),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='pedido',
            field=models.CharField(help_text='Bodega', max_length=10),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='producto',
            field=models.CharField(help_text='Clave del producto', max_length=10),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 11, 52, 48, 121448)),
        ),
    ]
