# Generated by Django 3.0.5 on 2021-04-13 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0017_auto_20210412_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parteCuenta1', models.CharField(help_text='Parte de la cuenta 1', max_length=5)),
                ('parteCuenta2', models.CharField(help_text='Parte de la cuenta 2', max_length=5)),
                ('parteCuenta3', models.CharField(help_text='Parte de la cuenta 3', max_length=5)),
                ('factura', models.CharField(help_text='No de Factura', max_length=20)),
                ('peridodContable', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('journalNumber', models.CharField(help_text='Nombre del canal', max_length=8)),
                ('monedaTransaccion', models.CharField(help_text='Moneda de transaccion', max_length=3)),
                ('montoMonedasistema', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montoMonedatransaccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.CharField(help_text='Descripción del descuento', max_length=100)),
                ('tipo', models.CharField(help_text='Tipo de descuento', max_length=3)),
                ('fechaFactura', models.DateTimeField(blank=True)),
                ('fechaInsercion', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 21, 8, 54, 199600))),
            ],
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 21, 8, 54, 185882)),
        ),
        migrations.AlterField(
            model_name='uuid_asw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 21, 8, 54, 189520)),
        ),
        migrations.AlterField(
            model_name='ventasasw',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 21, 8, 54, 196861)),
        ),
        migrations.AlterField(
            model_name='ventassap',
            name='fechaInsercion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 21, 8, 54, 198616)),
        ),
    ]
